name: Bug report
description: Report a bug in the app (stable or beta)
labels: ["bug"]
body:
  - type: dropdown
    id: channel
    attributes:
      label: Release channel
      description: Which version are you using?
      options:
        - Stable
        - Beta
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. 2.0.11
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Install source
      options:
        - GitHub Releases
        - IzzyOnDroid (F-Droid)
    validations:
      required: true

  - type: input
    id: android
    attributes:
      label: Android version
      placeholder: e.g. Android 14
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: Regression information (beta only)
      description: Did this work correctly in the latest stable version?
      placeholder: Yes / No / Not sure
